### ISSUE TITLE
Crates.io documentation

### ISSUE THREAD

**Issue by paperplanes53** [MindFlavor/AzureSDKForRust#104]
I get a 404 error when I try to access the documentation from crates.io.

**Comment by MindFlavor** [comment]
I have to wait for a new release to fix this. 
I'll put this as documentation link: [https://docs.rs/azure_sdk_for_rust](https://docs.rs/azure_sdk_for_rust) and this as homepage [https://mindflavor.github.io/AzureSDKForRust](https://mindflavor.github.io/AzureSDKForRust). 

If everything goes as planned docs.rs should give you the ability to change version on the fly.

**Comment by paperplanes53** [comment]
Thank you for the links!
