### ISSUE TITLE
Shared Access Signature support

### ISSUE THREAD

**Issue by promethe42** [MindFlavor/AzureSDKForRust#110]
Hi,

I need to create a `Client` authenticated with a [Shared Access Signature](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1).

AFAIK this is not supported yet.
How can I/where should I add this?

Thank you for your great work,

**Comment by promethe42** [comment]
OK I've found a working solution. I'll create a PR.

**Comment by MindFlavor** [comment]
Wow that was quick! 👍

**Comment by promethe42** [comment]
@MindFlavor please make a release soon so I can use it in my app :)
