### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [MindFlavor/AzureSDKForRust#12]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by MindFlavor** [comment]
Off the top of my head no, I mostly use it for ```base64``` & ```http encoding``` only. 
I had in mind to update the dependencies anyway (url and hyper have changed a lot since I've used them) so I'll switch to serde at the same time. 

Thank you for the heads up!

**Comment by MindFlavor** [comment]
Done in [https://github.com/MindFlavor/AzureSDKForRust/pull/14](https://github.com/MindFlavor/AzureSDKForRust/pull/14).
