### ISSUE TITLE
Support hyper-rustls

### ISSUE THREAD

**Issue by bmc-msft** [MindFlavor/AzureSDKForRust#120]
It would be great to include support for hyper-rustls, such that pure-rust clients could be built.

https://crates.io/crates/hyper-rustls

**Comment by MindFlavor** [comment]
That's a great idea, I love it! As soon as the tests complete (hopefully without errors) I will merge the above PR.

**Comment by MindFlavor** [comment]
Merged. I will publish the new version to Cargo ASAP.

**Comment by bmc-msft** [comment]
Are you going to publish the new version to cargo?

**Comment by MindFlavor** [comment]
Sorry I was busy, I'll try to do it next week at the latest.

**Comment by MindFlavor** [comment]
Published in [0.12.0](https://github.com/MindFlavor/AzureSDKForRust/releases/tag/0.12.0), sorry for the delay!
