### ISSUE TITLE
Fix travis failing because of lack of workspace support

### ISSUE THREAD

**Issue by MindFlavor** [MindFlavor/AzureSDKForRust#125]
Travis Ci does not work with the "meta" Cargo.toml. It must be corrected somehow.

**Comment by winding-lines** [comment]
I have a proposal for this: https://github.com/MindFlavor/AzureSDKForRust/pull/128

**Comment by MindFlavor** [comment]
Solved by [https://github.com/winding-lines](https://github.com/winding-lines) aforementioned PR.
