### ISSUE TITLE
Support for getting Shared Access Signatures

### ISSUE THREAD

**Issue by roqvist** [MindFlavor/AzureSDKForRust#147]
It would be great to be able to get Shared Access Signatures for blobs/containers, maybe something like:

```
client
    .get_sas()
    .with_blob_name(...) || with_container_name(...)
    .with_start(DateTime)
    .with_expiry(DateTime)
    .with_permissions(&[SasPermission::Read, SasPermission::Write, ...])
```

Also thanks for maintaining this really nice crate!

**Comment by MindFlavor** [comment]
Excellent idea! 
I'm working on it on this branch [issue/147/dev](https://github.com/MindFlavor/AzureSDKForRust/tree/issue/147/dev)!
