### ISSUE TITLE
Cosmos DB: url encode database names

### ISSUE THREAD

**Issue by Jibbow** [MindFlavor/AzureSDKForRust#150]
For requests with the Cosmos DB module, the database name is not properly encoded and requests will fail if they contain e.g. whitespaces.

When creating a database, the name is sent in the body as JSON and therefore arbitrary names are possible. When using other methods (like `get_database`) the name is in the URL.
The request might fail with "invalid URI bytes".

A solution would be to properly encode the database name.

And btw: Really nice project! :grin: :clap:

**Comment by MindFlavor** [comment]
Yes you are right! I am working on it!

**Comment by MindFlavor** [comment]
I just found out that, even though you can create databases/collections with arbitrary names, the Azure Auth does not handle them well (for instance, it breaks the Azure Data Explorer blade :face_with_head_bandage:). 
I will leave the dev branch online ([issue/150/dev](https://github.com/MindFlavor/AzureSDKForRust/tree/issue/150/dev)) if you want to play with it a bit. I will not persue this any longer though!
