### ISSUE TITLE
Cosmos DB: make required throughput optional when creating a new collection

### ISSUE THREAD

**Issue by Jibbow** [MindFlavor/AzureSDKForRust#151]
According to the docs https://docs.microsoft.com/de-de/rest/api/cosmos-db/create-a-collection the field `x-ms-offer-throughput` is optional.

When creating a collection with [`create_collection()`](https://docs.rs/azure_sdk_cosmos/0.23.0/azure_sdk_cosmos/struct.Client.html#method.create_collection) however it is strictly required.

**Comment by MindFlavor** [comment]
Indeed you are right! We should allow to specify either the throughput or the offer type (as required by [https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-a-collection](https://docs.microsoft.com/en-us/rest/api/cosmos-db/create-a-collection).

**Comment by MindFlavor** [comment]
Working branch is: [issue/151/dev](https://github.com/MindFlavor/AzureSDKForRust/tree/issue/151/dev).
