### ISSUE TITLE
Cosmos DB: create_collection() should not require an existing collection

### ISSUE THREAD

**Issue by Jibbow** [MindFlavor/AzureSDKForRust#152]
Right now, [`create_collection()`](https://docs.rs/azure_sdk_cosmos/0.23.0/azure_sdk_cosmos/struct.Client.html#method.create_collection) in Cosmos DB takes a reference to a `Collection` as a parameter (and sends a serialized version in the body of the request).
The reason for this is probably that that the according [REST endpoint](https://docs.microsoft.com/de-de/rest/api/cosmos-db/create-a-collection) requires a partial collection.

The required fields are:
 - Id (which is the name)
 - IndexingPolicy
 - PartitionKey

It would be much easier to understand and use if the `create_collection()` would just require a name and the other two parameters instead of a full collection.

**Comment by MindFlavor** [comment]
Sounds easy enough. The only question is how to call the method. Since Rust does not accept method overloading it must have a different name than `create_collection`.
