### ISSUE TITLE
Cosmos DB: fix replace_collection()

### ISSUE THREAD

**Issue by Jibbow** [MindFlavor/AzureSDKForRust#153]
The [`replace_selection()`](https://docs.rs/azure_sdk_cosmos/0.23.0/azure_sdk_cosmos/struct.Client.html#method.replace_collection) takes the name of the collection.
Then serializes the name, which just yields the name with quotes and then sends it to Azure and tries to create a collection.
This looks pretty much like a copy-paste bug :D 
And thinking about it this is more like `create_collection()` (also see #152 )

Docs for create collection: https://docs.microsoft.com/de-de/rest/api/cosmos-db/replace-a-collection

Sorry for all those issues :see_no_evil: 
I am currently working on #21 and #22 and these are issues I came across.

**Comment by MindFlavor** [comment]
I am rebuilding the CosmosDB API from scratch in order to be more similar to the storage one (see the [cosmos_same](https://github.com/MindFlavor/AzureSDKForRust/tree/cosmos_same) branch). I'll keep an eye on `replace_selection` and maybe add a proper test to avoid it happening again!

**Comment by Jibbow** [comment]
Nice! :grin:

**Comment by MindFlavor** [comment]
Shoud be ok now!
