### ISSUE TITLE
It seems as etag is missing from table storage API

### ISSUE THREAD

**Issue by gzp-crey** [MindFlavor/AzureSDKForRust#174]
Without etag no optimistic concurrency is possible and it seems as this functionality is missing completely from the table storage API.

scenario:
- read data with etag
- update data perform calculation
- replace if and only if tag matches

**Comment by gzp-crey** [comment]
Alos I'd suggest an beaking api change:
```
struct TableEntry<T> {
pub row_key: String,
pub partition_key: String,
pub etag: Option<String>, // none means etag check is disabled
payload: T, // raw, partition key is not included
}

pub fn get_entity<T: DeserializeOwned>(&self, table_name: &str) -> impl Future<Ok = TableEntry<T> ...>
pub fn insert_entity<T: Serialize>(&self, table_name: &str, entity: &TableEntry<T>) -> ...
pub fn update_entity<T: Serialize>(&self, table_name: &str, entity: &TableEntry<T>) -> ... 
```

**Comment by gzp-crey** [comment]
Any update or opinion on this change ? It is a blocking issue for me as there is no other way i'm aware of, to concurently update a row in a table. 
I can start working on it (depending on my time) , but not without your opinion as it is a  breaking change effecting multiple api.

**Comment by MindFlavor** [comment]
You are right, we need etag support. I've sketched something here (branch [issue/174/dev](https://github.com/MindFlavor/AzureSDKForRust/tree/issue/174/dev)). base on your - excellent - idea. In particular I have copied your `TableEntry` struct like this:

```rust
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableEntry<T> {
    #[serde(rename = "RowKey")]
    pub row_key: String,
    #[serde(rename = "PartitionKey")]
    pub partition_key: String,
    pub etag: Option<String>, // none means etag check is disabled
    #[serde(flatten)]
    pub payload: T, // raw, partition key is not included
}
```

Can you please try it and see if it makes sense for you?

I've added a new example to show the (temporary) new functions: [examples/entries.rs](https://github.com/MindFlavor/AzureSDKForRust/blob/issue/174/dev/azure_sdk_storage_table/examples/entries.rs). 

In a nutshell it creates a new entry than gets is back. It the updates it and gets it back again: 

```rust
    // get the entry (notice the etag)
    let ret: TableEntry<MyEntry> = table_service
        .get_entry2(&table_name, &my_entry.partition_key, &my_entry.row_key)
        .await?;
    println!("get_entry2 result == {:?}", ret);

    // now we update the entry passing the etag.
    my_entry.payload.my_value = "Wheel on the bus".to_owned();

    table_service
        .update_entry2("example", &my_entry, my_entry.etag.as_ref())
        .await?;
    println!("update_entry2 completed without errors");

    // get the entry again (new payload and etag)
    let ret: TableEntry<MyEntry> = table_service
        .get_entry2(&table_name, &my_entry.partition_key, &my_entry.row_key)
        .await?;
    println!("get_entry2 result == {:?}", ret);
```

PS: Sorry for the delay!

**Comment by MindFlavor** [comment]
I've just noticed that `update_entry2` function does not need the `etag` parameter since it's embedded in the struct. Making it mandatory makes explicit the choice of using optimistic concurrency or not so I do not know if it's a good idea to remove it.

**Comment by gzp-crey** [comment]
Wow, I did not expected a proto so fast :).
I'll take a closer look within a few days. 

For the update part I think the etag option can be removed and the one provided in the struct should be used. Having two distinct etag in a single operation will be confusing and I would not recomand.

Thanks again.

**Comment by gzp-crey** [comment]
Wow, I did not expected a proto so fast :).
I'll take a closer look within a few days. 

For the update part I think the etag option can be removed and the one provided in the struct should be used. Having two distinct etag in a single operation will be confusing and I would not recomand.

Thanks again.

**Comment by MindFlavor** [comment]
I have a PR for this: [https://github.com/MindFlavor/AzureSDKForRust/pull/180](https://github.com/MindFlavor/AzureSDKForRust/pull/180)! Please check it out!

**Comment by MindFlavor** [comment]
Merged in [table_0.30.2](https://github.com/MindFlavor/AzureSDKForRust/releases/tag/table_0.30.2).

**Comment by gzp-crey** [comment]
Thanks for your work. Unfortunately I've hit a brick wall with this incompatible half-updated low level crates (tokio, http, reqwest, actix-web). 
I've managed to sort out some of the issues (see my PR https://github.com/MindFlavor/AzureSDKForRust/pull/182) and now I can return to my original task. 

A small issue I've already detected is that update and insert operation don't return the new etag.
Maybe insert_entry (and update_entry) could be changed into:
```
pub async fn insert_entry<T>(&self, table_name: &str, entry: TableEntry<T>) -> Result<TableEntry<T>, AzureError>
```
Entry is consumed and the function returns a new one where etag is updated.

**Comment by cbrevik** [comment]
These changes seem like a good thing! 🎉 I have a couple of comments though:

The change from `entity` -> `entry` broke one of my builds. Not sure if this crate follows semver, but I'd recommend at least a minor bump (instead of patch). If not major. `Cargo.lock` should've saved me here, but it isn't used in one of my builds (I know..).

With this change, should `delete_entry` take in the actual entry? Seems like it only uses the `partition_key` and `row_key` anyway? I can send in an empty payload, so it's not a big deal. But it seems unnecessary.

**Comment by gzp-crey** [comment]
I've updated my PR with respect to the delete_entry (good point I had no use for delete at the moment).
My PR has other breaking changes: consuming entry and returning a new one and some function rename for easier use.

For the entry vs entity: I don't have strong opinion either is good for me. 
If @MindFlavor picks one I can update it in my PR if it is good for you all.

**Comment by gzp-crey** [comment]
@MindFlavor, @cbrevik  could you please review my PR #183 and comment if anything is still missing to merge it back to main ?
Thanks.

**Comment by MindFlavor** [comment]
Sorry for the delay! Excellent work BTW! :+1:

**Comment by gzp-crey** [comment]
It's ok. At least I had time to fix some bug :)
Thanks
I think it's time to close the issue.
