### ISSUE TITLE
parse storage connection string

### ISSUE THREAD

**Issue by ctaggart** [MindFlavor/AzureSDKForRust#178]
It would be great if there was a way to create a new storage account client from a storage account connection string. In .NET and other language SDKs, it is common to use the connection string.

It would simplify this a bunch by having two environment variables instead of four:
https://github.com/MindFlavor/AzureSDKForRust/blob/f30fb6e9ae540b067ca7ca39166093ff75690c8d/azure_sdk_storage_table/examples/copy_table.rs#L9-L23

**Comment by MindFlavor** [comment]
Yes I agree, something like `TableService::from_connection_string(&str)`. What do you think?

**Comment by ctaggart** [comment]
That would be great!

**Comment by ctaggart** [comment]
Unless you want to make a ConnectionString type.
``` rust
TableService::from_connection_string(&ConnectionString.parse(&str))
```

**Comment by ctaggart** [comment]
The .NET SDK for reference has:
https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#parsing-a-connection-string

Where CloudAccountStorage.Parse(string connectionString)
https://github.com/Azure/azure-storage-net/blob/7bb85351fda504ed0d40b720bb85a4eae22d365a/Lib/Common/CloudStorageAccount.cs#L514

The also have TryParse, so ConnectionString::parse should probably return a <Result, ConnectionString, Error>.

**Comment by ctaggart** [comment]
Probably more useful are the Tests. I just search for `DefaultEndpointsProtocol` to find them:

https://github.com/Azure/azure-storage-net/blob/4bd9460e0b9b007bdb34eaa1329de2257f7a34dc/Test/Common/Core/CloudStorageAccountTests.cs
