### ISSUE TITLE
Impact of "reqwest" dependency in azure_sdk_core crate

### ISSUE THREAD

**Issue by maxburke** [MindFlavor/AzureSDKForRust#212]
Hi,

I noticed the dependency of the `reqwest` crate in the `azure_sdk_core` crate is having an outsized impact on the size and time of my build. 

With it reqwest in azure_sdk_core, a clean unoptimized+debug build takes 136 s and results in a binary that is 183mb.

Without it, the same clean build takes 121 s and results in a 172mb binary, and trims 27 packages from the build.

Is this dependency always necessary in azure_sdk_core? If it is, could it at least be hidden behind a configuration option or something?

**Comment by MindFlavor** [comment]
Hi,
no, it is not. If I remember correctly it's only used to encapsulate the `reqwest::Error` in `AzureError` and even that only for the AAD crate. I'll try to remove it ASAP.

**Comment by MindFlavor** [comment]
I will also remove the `reqwest` crate dependency altogether from the AAD crate as soon as the OAuth2 crate stabilizes.

**Comment by maxburke** [comment]
Awesome news! :D

Thank you so much, I really appreciate it!
