### ISSUE TITLE
bump dependency versions

### ISSUE THREAD

**Issue by gzp-crey** [MindFlavor/AzureSDKForRust#214]
This is a tracking ticket to update the versions of the dependencies.
As there is a huge infrastructure update ongoing in the crates due to the async features, it'd be great if azure sdk is also updated to use the latest features.
- update to tokio 0.2
- update to http 0.2
- update to future 0.3
- update ring
- move dev-dependencies into dev section (ex env-logger)
- remove alpha and git based depenedencies

**Comment by gzp-crey** [comment]
All crates are updated but the aad due to the oauth2: ramosbugs/oauth2-rs#79

**Comment by gzp-crey** [comment]
I've managed to hack an oauth2 that has all the compatible features.
It required a very few modifications in the oauth2 (no api change).
So once the new oauth2 is out it should be enough to update the toml file only.

**Comment by roqvist** [comment]
Any updates on this?
Also, will this PR fix the following `hyper` conflict:

```
failed to select a version for `hyper`.
    ... required by package `azure_sdk_core v0.35.0`
    ... which is depended on by `azure_sdk_storage_blob v0.30.1`
    ... which is depended on by `my_app v0.1.1 (...path...)`
versions that meet the requirements `^0.13.0-alpha.4` are: 0.13.1, 0.13.0, 0.13.0-alpha.4

the package `azure_sdk_core` depends on `hyper`, with features: `unstable-stream` but `hyper` does not have these features.


all possible versions conflict with previously selected packages.

  previously selected package `hyper v0.13.1`
    ... which is depended on by `azure_sdk_core v0.35.0`
    ... which is depended on by `azure_sdk_storage_blob v0.30.1`
    ... which is depended on by `my_app v0.1.1 (...path...)`

failed to select a version for `hyper` which could resolve this conflict
```

**Comment by MindFlavor** [comment]
I'm waiting for the green-light from @gzp-crey. When he deems this PR ready I will merge it. The only constraint I have is for it to compile successfully (we have Travis for that). The e2e tests can be fixed at later date.

**Comment by roqvist** [comment]
I'm working on a project with an up-to-date Actix (2.0) and eagerly awaiting this so I forked and merged the current PR to test it myself loaclly, I found the following:

- I had to add the `failure` crate in Cargo.toml for `azure_sdk_core`
  - Not sure why, `failure` doesn't seem to be new to this PR. Maybe one of the removed/moved dependencies had this and now it's missing?
- Creating a storage client (`azure_sdk_storage_core::client::Client::new(...)`) from within a running Actix system panics with:
`thread 'main' panicked at 'cannot access native cert store: Custom { kind: InvalidData, error: BadDER }', src\libcore\result.rs:1165:5`

Using Rust 1.40.0 on Windows 10 (`stable-x86_64-pc-windows-msvc` toolchain).

**Comment by gzp-crey** [comment]
@roqvist: I've merge it to main and failure was added as a dependency.

**Comment by gzp-crey** [comment]
@MindFlavor Unfortunately it still has a hacked dependency (oauth2) that is still using my fork from git.
If someone can solved it, I think it can be merged but not before.

**Comment by gzp-crey** [comment]
ouath2 is still used from github, but this time it's the "official" master branch.

**Comment by gzp-crey** [comment]
I was waiting to eagerly for oath2 alpah.10, but it turned out it is working just fine with alpha.9
So all the crates are used from the crates.io and there are no more hacks.
So I think the PR is ready to be merged back to main.

The only thing that is not so nice is that there is still one alpha dependency, but I think it was not an issue before.
