### ISSUE TITLE
Builder for TableStorage Query

### ISSUE THREAD

**Issue by gzp-crey** [MindFlavor/AzureSDKForRust#217]
For now it is quite hard to create a well formed query for the table storage.
It'd be great to have a builder where 
- $filter is constructed from "abstract" items
- $top
- $select
- Value parameters are escaped automatically to avoid injection vulnerability

The best would be if $filter and $select were aware of the structure of the payload, but I think that'd require some macro magic unless serde provides some "reflection" info.

(Similar to https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablequery.generatefiltercondition?view=azure-dotnet#Microsoft_Azure_Cosmos_Table_TableQuery_GenerateFilterCondition_System_String_System_String_System_String_)

**Comment by MindFlavor** [comment]
I agree, a builder would be nice, at least with the arguments you specified. As for the reflection, I too think it would require a (cumbersome) procedural macro.

**Comment by gzp-crey** [comment]
triage - outdated for me
