### ISSUE TITLE
Rename Entry to entity

### ISSUE THREAD

**Issue by gzp-crey** [MindFlavor/AzureSDKForRust#224]
It's rather a question than an issue. According to c# and MS docs the rows in a table storage are called entity and my original entry naming was a typo.

What do you think about renaming entry to entity ?
including functions, types, etc:
- TableEntity
- get_entity
- insert_entity
- etc.

**Comment by MindFlavor** [comment]
I guess it makes sense. Even if it will be a breaking change it's just a find/replace type of one!

**Comment by gzp-crey** [comment]
If the PR is accepted please don't forget to update the semver version :).

**Comment by MindFlavor** [comment]
I'll prepare a new, global version ASAP.
