### ISSUE TITLE
table storage, missing eteg for query_entites

### ISSUE THREAD

**Issue by gzp-crey** [MindFlavor/AzureSDKForRust#229]
It seems as etag is not parsed for streamed query.

It is sent back in the full metadata (https://docs.microsoft.com/en-us/rest/api/storageservices/query-entities):
"odata.etag":"W/\"0x5B168C7B6E589D2\""

For api consistency it'd be good if timestamp and etag is returned for all table operations.

Maybe if full metadata is requested for all operation, the sdk could be simplified and parse etag from metadata instead of header. (Not tested)

**Comment by MindFlavor** [comment]
I agree, the `etag` should be returned regardless of the function called.  Good catch.
