### ISSUE TITLE
All requests fail if "localhost" is used to set up an emulator connection

### ISSUE THREAD

**Issue by Tomcc** [MindFlavor/AzureSDKForRust#230]
I've been puzzling on this one for a while :)

I was trying to interact with Azurite, so I set up my client like this:
```rust
    let blob_storage_url = Url::parse("http://localhost:10000")?;
    let table_storage_url = Url::parse("http://localhost:10002")?;
    let client = Client::emulator(&blob_storage_url, &table_storage_url)?;
```
however any request made with that client would straight up panic immediately.

I dug around a little bit and I finally found this suspicious code in `rest_client.rs`:
```rust
fn get_account(u: &url::Url) -> &str {
    match u.host().unwrap().clone() {
        url::Host::Domain(dm) => {
            // debug!("dom == {:?}", dm);

            let first_dot = dm.find('.').unwrap();  // <---- Panic happens here!
            &dm[0..first_dot]
        }
        url::Host::Ipv4(_) => {
            // this must be the emulator
            "devstoreaccount1"
        }
        _ => panic!("only Domains are supported in canonicalized_resource"),
    }
}
```
The issue is that urls created with `localhost` actually match the `Domain` case, but they have no dot and panic.
This may be a simple fix but I'm not familiar enough with this to make a change... For now, initializing the emulator with `127.0.0.1` was a good workaround.

**Comment by MindFlavor** [comment]
This is definitely a bug. I should have checked for "localhost" as well as the IP Address when identifying the emulator. 

Thank you for providing the debug, analysis, and the workaround! 
I'll prepare a fix as soon as possible (you did all the work so it should be fairly easy).

**Comment by Tomcc** [comment]
That's great, thanks :)

One nitpick though... I'm not sure that in general it's possible to guess if someone is using an emulator from the IP. What if I'm hosting the emulator on my raspberry pi or something?

Intuitively, `Client`s created through `Client::emulator` should use the dev account no matter what. Maybe `get_account` should take a `emulator: bool` to disambiguate? That's probably more work, but it'd be more correct I think.

**Comment by MindFlavor** [comment]
> Intuitively, `Client`s created through `Client::emulator` should use the dev account no matter what. 

Yes. And it should also be possible to disambiguate at compile time without the runtime check (maybe using a trait?). I'll think of something but if it ends up entailing too many changes I'll go the easy route and store a bool `is_emulator` somewhere and check it at runtime.

**Comment by MindFlavor** [comment]
> And it should also be possible to disambiguate at compile time without the runtime check (maybe using a trait?). I'll think of something but if it ends up entailing too many changes I'll go the easy route and store a bool `is_emulator` somewhere and check it at runtime.

Scratch that, I was wrong. In order to make different types between Azure client and emulator the Client interface should be a trait object (if we want to keep the same API between the two) so we'll be using dynamic dispatch almost everywhere. I'm not  sure it's worth saving the `is_emulator` bit. I'll make some more tests and get back to you.

**Comment by MindFlavor** [comment]
Turns out we do not need the `get_account` function at all since the `Client` already has the account member (fixed for the emulator, variable for Azure). With some minor changes of the `rest_client` functions (now accepting a simple trait instead of one or more parameters) we can ask directly the `Client` for its account. 

@Tomcc: I do not have e2e test for the emulator right now, can you test the aforementioned PR and get back to me?

**Comment by Tomcc** [comment]
@MindFlavor I tried in my local setup, it looks like it works just fine with `localhost:10000` now.

I'm not sure about the Traits discussion, I'm still not very used to writing traits... but it makes sense from what I can tell!

Thanks for the change!

**Comment by MindFlavor** [comment]
Thank you for debugging, providing a solution and testing it! :+1:
