### ISSUE TITLE
storage_table V2.0

### ISSUE THREAD

**Issue by gzp-crey** [MindFlavor/AzureSDKForRust#234]
Based on my latest experiences I've created a new implementation for the storage_table based on your works:
TableClient: The table management API (create, list for now)
CloudTable: Manage the content of a single table
Batch operation: work in progress I have to understand how it works in depth, but the plan is to remove the uniform operation limit.

The meta information is not exposed on the API and managed internally to handled etag and timestamp as fluent as possible. Side effect: using Hashmap, serde_json::Value as input output may have undesired behavior as "odata.*" properties get (de)serialized.

Please check the new API and crate structure.

I'm open to any suggestion, change request.

(Should resolve , #224, #229) 

**Edit**
Things to improve:
 - use the same request builder for batch and single operation
 - escape inputs and/or check for invalid characters to avoid injection vulnerabilities
- useing the IgnoredAny concept to skip deserializing meta data for HashMap, serde_json:Value like TableEntity payloads (https://serde.rs/ignored-any.html)
 - use enum based odata type to serialize datetime in "native" format (https://github.com/serde-rs/serde/issues/760#issuecomment-499570311)
 - add the MERGE functionalty (I had no use for this and have no idea what is a typical usecase)

**Comment by gzp-crey** [comment]
Please review my changes. I'm open to any discussion how to make it more ergonomic and how to improve it.

**Comment by MindFlavor** [comment]
I like it very much. I myself do not know the use of the merge functionality so we can postpone it for now.
