### ISSUE TITLE
Dependency conflict when azure_sdk_auth_aad used outside of the git repo

### ISSUE THREAD

**Issue by imp** [MindFlavor/AzureSDKForRust#236]
I am trying to use `azure_sdk_auth_aad` crate for the sake of ARM support prototyping (#177). However, it seems the published version of this crate is not consistent with the in-repo version.

When I add a dependency on `azure_sdk_auth_aad` as well as `reqwest` in Cargo.toml
```
[dependencies]
azure_sdk_auth_aad = "0.35"
reqwest = { version = "0.10", features = ["json"] }

```
I am getting dependency conflict
```
    Updating crates.io index
error: failed to select a version for `hyper`.
    ... required by package `azure_sdk_core v0.35.0`
    ... which is depended on by `azure_sdk_auth_aad v0.35.0`
    ... which is depended on by `azure_sdk_arm v0.1.0 (/Volumes/replixio/azure_sdk_arm)`
versions that meet the requirements `^0.13.0-alpha.4` are: 0.13.2, 0.13.1, 0.13.0, 0.13.0-alpha.4

the package `azure_sdk_core` depends on `hyper`, with features: `unstable-stream` but `hyper` does not have these features.


all possible versions conflict with previously selected packages.

  previously selected package `hyper v0.13.0`
    ... which is depended on by `azure_sdk_core v0.35.0`
    ... which is depended on by `azure_sdk_auth_aad v0.35.0`
    ... which is depended on by `azure_sdk_arm v0.1.0 (.../azure_sdk_arm)`

failed to select a version for `hyper` which could resolve this conflict
```

Perhaps you need to publish `azure_sdk_auth_aad` on crates.io that will depend on `azure_sdk_core` 0.36 - similar to how it works in the git repository?

**Comment by MindFlavor** [comment]
The whole project is due to a new, global, release. I'll bump the version of all the crates to the same level, provided they compile :relaxed: .

**Comment by MindFlavor** [comment]
I am waiting for the PR [https://github.com/MindFlavor/AzureSDKForRust/pull/237](https://github.com/MindFlavor/AzureSDKForRust/pull/237) to be merged and then I'll publish everything.

**Comment by MindFlavor** [comment]
The version [0.40.0](https://github.com/MindFlavor/AzureSDKForRust/releases/tag/0.40.0) is out. Can you please try now?

**Comment by imp** [comment]
Confirming, it works! Thanks!
