### ISSUE TITLE
Cosmos: Run a query in a BoxFuture

### ISSUE THREAD

**Issue by glademiller** [MindFlavor/AzureSDKForRust#241]
I have the need to run a query in context that I have to have a future that is Send + Sync but as far as I can figure out because with_database and with_collection take &'a dyn DatabaseName the resulting QueryBuilder is !Send and !Sync. This could be me missing something obvious but so far I haven't found a way future that is usable when using Cosmos DB via this crate. 

I would really appreciate any guidance figuring this out.

**Comment by MindFlavor** [comment]
Yes, there are no constraints right now in the traits (besides `Debug`). 
I've created a branch ([issue/241/dev](https://github.com/MindFlavor/AzureSDKForRust/tree/issue/241/dev)) and the relative tentative PR (#245) with the added constraints. 

Can you please check if it helps? 
Also, if can you please provide us simple repro we will try to solve this without adding additional trait constraints.

**Comment by MindFlavor** [comment]
This should be superseded (from v0.100.0 onwards the requests have been modified). I'll close it, if need be please reopen it!
