### ISSUE TITLE
Cosmos: Need to set partition key on execute store procedure

### ISSUE THREAD

**Issue by glademiller** [MindFlavor/AzureSDKForRust#242]
Cosmos won't let me execute the stored procedure and there is no way to set the partition key on the stored procedure request.
```
The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.
```

**Comment by MindFlavor** [comment]
Can you please give me a repro stored procedure? I've just updated the stored procedure code but I haven't added the `PartitionKeysRequired` trait (nor the optional one) since I'm unable to reproduce your issue.

**Comment by glademiller** [comment]
I will take a look today thank you for taking a look.

**Comment by glademiller** [comment]
Your branch does solve my problem.

**Comment by MindFlavor** [comment]
Great! I'll merge it.
