### ISSUE TITLE
Implement Sync for AzureError

### ISSUE THREAD

**Issue by nbigaouette** [MindFlavor/AzureSDKForRust#259]
I'm trying to bootstrap a simple project talking to an azure blob storage. To simplify error handling I want to use the [`anyhow` crate](https://crates.io/crates/anyhow).

Unfortunately I cannot make both crates work. `anyhow` complains that the `AzureError` is not sync:

```
error[E0277]: `(dyn std::error::Error + std::marker::Send + 'static)` cannot be shared between threads safely
  --> end2end/src/main.rs:42:72
   |
42 |     let client = Client::new("your_storage_account", "your_master_key")?;
   |                                                                        ^ `(dyn std::error::Error + std::marker::Send + 'static)` cannot be shared between threads safely
   |
   = help: the trait `std::marker::Sync` is not implemented for `(dyn std::error::Error + std::marker::Send + 'static)`
   = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<(dyn std::error::Error + std::marker::Send + 'static)>`
   = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + std::marker::Send + 'static)>`
   = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + std::marker::Send + 'static)>>`
   = note: required because it appears within the type `error_chain::State`
   = note: required because it appears within the type `serde_xml_rs::error::Error`
   = note: required because it appears within the type `azure_sdk_core::errors::AzureError`
   = note: required because of the requirements on the impl of `std::convert::From<azure_sdk_core::errors::AzureError>` for `anyhow::Error`
   = note: required by `std::convert::From::from`
```
where main the signature is `fn main() -> anyhow::Result<()>`.

Looking around anyhow github issue, it seems to want a `Sync` error to be able to work in `async` code: https://github.com/dtolnay/anyhow/issues/81 

And according to https://github.com/dtolnay/anyhow/issues/72, errors should be Sync (see comment https://github.com/dtolnay/anyhow/issues/72#issuecomment-599240738)

Could `AzureError` be made `Sync`?

Looking at the compiler error, is seems `error_chain` is an indirect dependency (through `serde_xml`), which could potentially block this... Any though?

Thanks!

**Comment by MindFlavor** [comment]
Your guess was right, now `AzureError` is both `Send` and `Sync` :champagne::champagne::champagne:  !

I've added some pseudo unit tests to check this:

https://github.com/MindFlavor/AzureSDKForRust/blob/4ab45293ed7f724bbcd830a2c48a90b71476a8ab/azure_sdk_core/src/errors.rs#L439-L480

This way if something not `Send` and/or `Sync` slips through the cracks in the future we will be notified.

**Comment by nbigaouette** [comment]
Great! Thanks a lot!

For the tests that fail to compile, there is a feature of doc tests that could be useful: https://doc.rust-lang.org/edition-guide/rust-2018/rustdoc/documentation-tests-can-now-compile-fail.html
That would require moving the "non-compilable tests" to doc-tests, but it might be possible.
