### ISSUE TITLE
Please update dependency on serde-xml-rs to 0.4

### ISSUE THREAD

**Issue by nbigaouette** [MindFlavor/AzureSDKForRust#260]
The crate `azure_sdk_core` depends on `serde-xml-rs` 0.3, which is itself depends on `error-chain`. See https://github.com/RReverser/serde-xml-rs/blob/0.3.0/Cargo.toml#L13

Version 0.4 switched to `thiserror` instead (https://github.com/RReverser/serde-xml-rs/blob/0.4.0/Cargo.toml#L13), which should be preffered over (unmaintained) `error-chain`.

Also, this could potentially fix #259.

**Comment by MindFlavor** [comment]
I'm going to close this as soon as I publish the crates updated by you in crates.io.
