### ISSUE TITLE
`Box<dyn Client + Send + Sync>` doesn't implement the `Blob` trait

### ISSUE THREAD

**Issue by cswinter** [MindFlavor/AzureSDKForRust#292]
I am trying to figure out how to store a reusable instance of the `BearerTokenClient` in a struct that might be moved between/accessed by different threads. The `azure_sdk_sotrage_core::bearer_token_client` module is private and I haven't found any other export that allows referring to the `BearerTokenClient` type directly. Preferably I would just use `Box<dyn Client + Send + Sync>` to allow for different client implementations, but this doesn't seem to implement `Client` and I have so far been unable to figure out how to make the types work out. Full compile error:

```
error[E0599]: no method named `put_block` found for struct `std::boxed::Box<(dyn azure_sdk_storage_core::client::Client + std::marker::Sync + 'static)>` in the current scope
   --> src/blobstore/azure_blob_storage.rs:77:18
    |
77  |                 .put_block()
    |                  ^^^^^^^^^ method not found in `std::boxed::Box<(dyn azure_sdk_storage_core::client::Client + std::marker::Sync + 'static)>`
    |
   ::: /Users/clemens/.rustup/toolchains/nightly-2020-05-01-x86_64-apple-darwin/lib/rustlib/src/rust/src/liballoc/boxed.rs:159:1
    |
159 | pub struct Box<T: ?Sized>(Unique<T>);
    | -------------------------------------
    | |
    | doesn't satisfy `_: azure_sdk_storage_blob::Blob<std::boxed::Box<dyn azure_sdk_storage_core::client::Client + std::marker::Sync>>`
    | doesn't satisfy `_: azure_sdk_storage_core::client::Client`
    |
   ::: /Users/clemens/.cargo/registry/src/github.com-1ecc6299db9ec823/azure_sdk_storage_core-0.44.0/src/client.rs:16:1
    |
16  | pub trait Client {
    | ----------------
    | |
    | doesn't satisfy `_: azure_sdk_storage_blob::Blob<dyn azure_sdk_storage_core::client::Client + std::marker::Sync>`
    | doesn't satisfy `_: std::marker::Sized`
    |
    = note: the method `put_block` exists but the following trait bounds were not satisfied:
            `std::boxed::Box<dyn azure_sdk_storage_core::client::Client + std::marker::Sync>: azure_sdk_storage_core::client::Client`
            which is required by `std::boxed::Box<dyn azure_sdk_storage_core::client::Client + std::marker::Sync>: azure_sdk_storage_blob::Blob<std::boxed::Box<dyn azure_sdk_storage_core::client::Client + std::marker::Sync>>`
            `dyn azure_sdk_storage_core::client::Client + std::marker::Sync: std::marker::Sized`
            which is required by `dyn azure_sdk_storage_core::client::Client + std::marker::Sync: azure_sdk_storage_blob::Blob<dyn azure_sdk_storage_core::client::Client + std::marker::Sync>`
```

**Comment by MindFlavor** [comment]
The error is a weird one: to get around it I've implemented manually `Client` for `Box<dyn Client>` (weird, I know, but it makes using a boxed instance seamless): 

https://github.com/MindFlavor/AzureSDKForRust/blob/f746e3666da7dfdfbcc45d18534827a4565905e2/azure_sdk_storage_core/src/client.rs#L46-L75

Your code does not work because I forgot to implement `Client` for `Box<dyn Client + Send +Sync>` (so it's my fault :man_facepalming: ). 
I think the easiest and cleanest way is to require `Client` to also be `Send + Sync`. I'm preparing a PR now, after that your code should compile as it is!

**Comment by MindFlavor** [comment]
I've merged the change, please let me know if it helps!

**Comment by cswinter** [comment]
compiler has stopped shouting at me 10/10 🎉
