### ISSUE TITLE
Look into 'DefaultAzureCredential' pattern

### ISSUE THREAD

**Issue by damienpontifex** [MindFlavor/AzureSDKForRust#300]
A few of the azure sdk packages have a `DefaultAzureCredential` type that enables ease of developing locally (where it might use your locally logged in azure cli) and then running the same thing in Azure (or anywhere else) with managed identity or client id/secret. See https://azure.github.io/azure-sdk/posts/2020-02-25/defaultazurecredentials.html

Is this something this library would be open to having implimented/move towards?

Brief play with code might look something like:

```rust
struct AccessToken {
  pub token: String,
  pub expires_on: DateTime<Utc>,
}

#[async_trait::async_trait]
pub trait TokenCredential {
    async fn get_token(&self, resource: &str) -> Result<AccessToken, AzureError>;
}

pub struct EnvironmentCredential;
pub struct ManagedIdentityCredential;
pub struct AzureCliCredential;

// Each of these would impl TokenCredential e.g.
impl TokenCredential for AzureCliCredential {
}
```

Looking at the C# implementation as another reference https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs the DefaultCredential here might be something like:
```rust
pub struct DefaultCredential {
    sources: Vec<Box<dyn TokenCredential + Send + Sync>>,
}

impl Default for DefaultCredential {
    fn default() -> Self {
        DefaultCredential {
            sources: vec![
                Box::new(EnvironmentCredential {}),
                Box::new(ManagedIdentityCredential {}),
                Box::new(AzureCliCredential {}),
            ],
        }
    }
}

#[async_trait::async_trait]
impl TokenCredential for DefaultCredential {
    async fn get_token(&self, resource: &str) -> Result<TokenResponse, AzureError> {
        for source in &self.sources {
            if let Ok(token) = source.get_token(resource).await {
                return Ok(token);
            }
            // TODO: bubble up err events from individual implementations
        }

        return Err(AzureError::GenericErrorWithText(
            "End of default list".to_owned(),
        ));
    }
}

```

I'd like to contribute towards this end, but wanted to open an issue/discussion before committing or moving forward to the acceptance of this and aligning with the approach developed in the library already

**Comment by MindFlavor** [comment]
It seems useful! Definitely go for it!
The Azure AD crate is in flux (it's the most recent, in dev crate) and needs a reorg in terms of struct/traits. Maybe your `TokenCredential` trait could be a good candidate to standardize the access tokens as well. 

Maybe @davide-rota can chip in here as well: he's much more competent about authentication/authorization than me.
