### ISSUE TITLE
put_block_list requires x-ms-content-crc64

### ISSUE THREAD

**Issue by MindFlavor** [MindFlavor/AzureSDKForRust#302]
~~The updated REST API no longer returns `x-ms-content-crc64` but the crate still requires it. The code must be corrected or any call will fail with `Header not found: x-ms-content-crc64`~~

**Comment by MindFlavor** [comment]
@cswinter : I was hasty in creating this issue but I am not able to reproduce it. Can you please make sure you are using the latest version of the crates?

Crate | Version
-- | --
azure_sdk_storage_blob | 0.44.1
azure_sdk_core  | 0.43.4
azure_sdk_storage_core | 0.44.1

(also please throw in a `cargo clean && cargo update` for good measure :+1:)

**Comment by cswinter** [comment]
Still running into the same error. Dependencies:
```
[dependencies]
azure_sdk_storage_blob = "0.44.1"
azure_sdk_core = "0.43.4"
azure_sdk_storage_core = "0.44.1"
azure_sdk_auth_aad = "0.46.0"
color-eyre = "0.4"
tokio = { version = "0.2", features = ["full"] }
oauth2               = { version = "3.0.0-alpha.9", features = ["reqwest-010", "futures-03"], default-features = false}
reqwest              = { version = "0.10", features = ["json"] }
md5 = "0.7"
```

**Comment by cswinter** [comment]
Full code: https://github.com/cswinter/azure-blob-service-principal-test

**Comment by MindFlavor** [comment]
Thanks for the repro @cswinter: using your code I managed to pin down the cause! 

It seems that **not** passing the `Content-md5` header in the request causes Azure to return the `x-ms-content-crc64` header in the response (my example case). If `Content-md5` is specified the returned headers do not include `x-ms-content-crc64` (your case). 

It's documented: 
[https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#response-headers](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#response-headers). 

I will make the field optional in the response and add an e2e test so it won't slip again in the future!

**Comment by cswinter** [comment]
Thanks so much, it seems to be all working now! I've kicked off some tests that have so far performed maybe 1000 downloads of checksummed blobs.
