### ISSUE TITLE
Clarification on LoginResponse

### ISSUE THREAD

**Issue by cswinter** [MindFlavor/AzureSDKForRust#305]
It's not clear to me from the [LoginResponse docs](https://docs.rs/azure_sdk_auth_aad/0.46.1/azure_sdk_auth_aad/struct.LoginResponse.html) what the units for `expires_in` and `ext_expires_in` are (I assume seconds?).
What is the difference between `expires_in`, `ext_expires_in`, `expires_on` and `not_before`?
When can I expect `expires_on` and `not_before` to be populated?
Possibly there's some Azure docs that answer these questions, but I haven't been able to find them at least after a cursory search so I would be useful to link to them from the Rust docs.

**Comment by MindFlavor** [comment]
The documentation has only three fields ([v2-oauth2-client-creds-grant-flow#successful-response-1](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#successful-response-1)): `access_token`, `token_type` and `expires_in`. The "extra" fields happen to be returned but are not documented so maybe it's better if we ignore it (I might remove them altogether in a future release or make them private).

**Comment by cswinter** [comment]
Ah, I knew there must be docs somewhere. Thanks for the explanation!
