### ISSUE TITLE
`Arc<dyn Client>` doesn't implement `Blob` trait

### ISSUE THREAD

**Issue by cswinter** [MindFlavor/AzureSDKForRust#307]
Similar to https://github.com/MindFlavor/AzureSDKForRust/issues/292, `Arc<dyn Client>` doesn't seem to work, though `Arc<Box<dyn Client>>` does. Maybe the best way to support all pointer types is actually to implement `Client` for `&dyn Client` or something? I would assume this kind of problem is frequent enough in Rust that there is some canonical solution, though I don't myself know what it is.

**Comment by MindFlavor** [comment]
I guess it has something to do with `?Sized` (and my improper handling of it). I'm opening a PR to try and fix this.

**Comment by MindFlavor** [comment]
@cswinter : can you please test the PR and tell me if it helps? Thanks!

**Comment by cswinter** [comment]
Tested the PR, seems to work 🎉

**Comment by MindFlavor** [comment]
Thank you for your help!
