### ISSUE TITLE
Getting HeaderNotFound `x-ms-content-crc64` on put_block_blob for Azurite

### ISSUE THREAD

**Issue by perfectayush** [MindFlavor/AzureSDKForRust#311]
I am developing a project, currently locally, with azurite, but in production it will use Azure Cloud.  

I am facing issues with `put_block_blob` API  
This issue is similar to #302 but I am facing it with azurite. Response for the api is giving:
``` 
Err(HeaderNotFound( "x-ms-content-crc64",))
```

Inspecting code it looks like both md5 and crc64 are expected for `PutBlockBlobResponse`
Changing it to return consistency with `consistency_from_headers` fixes the response.

Not sure if it will happen with a container in Azure Cloud, currently not testing with Cloud.

**Comment by MindFlavor** [comment]
Yes, you are right, the correct way is to return a `Consistency` enum. I will fix it ASAP!

**Comment by MindFlavor** [comment]
@perfectayush: I took your suggestion and implemented it in the aforementioned PR. Let me know if it solves your issue! Thanks!

**Comment by perfectayush** [comment]
@MindFlavor Thanks, the changes have resolved my errors.
