### ISSUE TITLE
cannot list blobs

### ISSUE THREAD

**Issue by adminSxs** [MindFlavor/AzureSDKForRust#315]
![image](https://user-images.githubusercontent.com/15902505/87867511-2632f900-c9c0-11ea-8eb9-c6361c3a0ffe.png)

**Comment by MindFlavor** [comment]
The error happens because `list_blobs` requires a cloneable client. This is just a requirement for the `stream` function (that you are not using) so I'll be removing it in ASAP.
In the meantime if you can use an `Arc<dyn Client>` instead of a `Box<dyn Client>` the error will disappear.
