### ISSUE TITLE
Blob "put" has lifetime issues

### ISSUE THREAD

**Issue by ajsyp** [MindFlavor/AzureSDKForRust#33]
Right now, `Blob::put` takes a generic lifetime `'b`. This works fine when submitting jobs to a Tokio Core using `Core::run`. However, trying to use `Handle::spawn` will result in a lifetime conflict. I'm definitely not the expert, but maybe this is due to different lifetime requirements between `Core::run` and `Handle::spawn` which are interacting poorly with the compiler-inferred lifetime in `Blob::put`.

Here is a minimum working example demonstrating the problem (all dependency versions match those of AzureSDKForRust's Cargo.toml):

```
extern crate azure_sdk_for_rust;
extern crate hyper;
extern crate chrono;
extern crate tokio_core;
extern crate futures;

use hyper::mime::Mime;
use tokio_core::reactor::Core;
use futures::future::*;
use azure_sdk_for_rust::azure::storage::client::Client;
use azure_sdk_for_rust::azure::storage::blob::{Blob, BlobType, PUT_OPTIONS_DEFAULT};
use azure_sdk_for_rust::azure::core::lease::{LeaseState, LeaseStatus};

/// Just create a test Blob.
fn create_blob(data: &[u8]) -> Blob {
    Blob {
        name: "nameOfBlob".into(),
        container_name: "containerName".into(),
        snapshot_time: None,
        last_modified: chrono::Utc::now(),
        etag: "".to_owned(),
        content_length: data.len() as u64,
        content_type: Some("text/plain".parse::<Mime>().unwrap()),
        content_encoding: None,
        content_language: None,
        content_md5: None,
        cache_control: None,
        x_ms_blob_sequence_number: None,
        blob_type: BlobType::BlockBlob,
        lease_status: LeaseStatus::Unlocked,
        lease_state: LeaseState::Available,
        lease_duration: None,
        copy_id: None,
        copy_status: None,
        copy_source: None,
        copy_progress: None,
        copy_completion: None,
        copy_status_description: None
    }
}

fn main() {
    let mut core = Core::new().unwrap();
    let client = Client::new(&core.handle(), "storageAccount", "accountKey").unwrap();

    let data = b"someData";
    let blob = create_blob(&data[..]);

    let future = blob.put(
        &client,
        &PUT_OPTIONS_DEFAULT,
        Some(&data[..])
    ).then(move |res| {
        // Handle the result.
        // This is needed because `Handle::spawn` requires that the future it
        // is given be Future<Item=(), Error=()>.
        match res {
            Ok(_) => ok(()),
            Err(_) => err(())
        }
    });

    // THIS WORKS:
    //core.run(future).unwrap();

    // BUT THIS DOES NOT:
    let handle = core.handle();
    handle.spawn(future);
    // Assume the core is running...
}
```

The compiler error is:

```
error[E0597]: `client` does not live long enough
  --> src/main.rs:50:4
   |
50 |         &client,
   |          ^^^^^^ borrowed value does not live long enough
...
70 | }
   | - borrowed value only lives until here
   |
   = note: borrowed value must be valid for the static lifetime...
```

For my use case, I can fix the problem by removing the generic lifetime `'b` altogether from `Blob::put`, like so (line 566 of `src/azure/storage/blob/mod.rs`):

```
    pub fn puts(
        &self,
        c: &Client,
        po: &PutOptions,
        r: Option<&[u8]>,
    ) -> impl Future<Item = (), Error = AzureError> {
```

However, I don't know if this will break others' use cases. If you feel that removing the generic is the right way to go, let me know and I can submit a PR.

**Comment by MindFlavor** [comment]
Yes you are right, there is no need to constrain the `client` to the same lifetime of the returned future. IIRC, I've added this convoluted lifetime decoration because of this: [https://users.rust-lang.org/t/solved-trouble-with-named-lifetimes-in-chained-futures/11943](https://users.rust-lang.org/t/solved-trouble-with-named-lifetimes-in-chained-futures/11943), but it seems that it's no longer needed. 

Please submit the PR, I'll merge it so you can get proper credit. 

PS: I've already added an example - now failing - called `blob01.rs`  with your repro. I will try and add it to the end-to-end tests as soon as it works.

**Comment by MindFlavor** [comment]
Should be solved by [https://github.com/MindFlavor/AzureSDKForRust/releases/tag/0.6.1](https://github.com/MindFlavor/AzureSDKForRust/releases/tag/0.6.1).
