### ISSUE TITLE
You are awesome.

### ISSUE THREAD

**Issue by thedodd** [MindFlavor/AzureSDKForRust#40]
Thank you for making a futures based API for object storage (as well as the other interfaces, but especially object storage). The google & AWS SDKs out there for rust, as of now, do not have futures based interfaces.

Also, sorry for spamming your issues list ... I just really felt compelled to put a good word in for you. Feel free to close whenever `:)`.

**Comment by MindFlavor** [comment]
Thank you for your kind words! Much appreciated!

Gratitude is the only think I'm getting out of this so it really warms my hearth!

Thank you again!
