### ISSUE TITLE
Docs for 0.6.1 & 0.7.0 failed to build on docs.rs.

### ISSUE THREAD

**Issue by thedodd** [MindFlavor/AzureSDKForRust#41]

**Comment by MindFlavor** [comment]
It seems the docs.rs cargo is outdated. From the build log:

```
error[E0658]: `impl Trait` in return position is experimental (see issue #34511)
   --> .cargo/registry/src/github.com-1ecc6299db9ec823/azure_sdk_for_rust-0.7.1/src/azure/core/errors.rs:190:6
    |
190 | ) -> impl Future<Item = (hyper::StatusCode, hyper::Headers, Vec<u8>), Error = AzureError> {
    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable
```

This kind of error should not happen from rust 1.26 on as ```impl Trait``` has been stabilized: [https://blog.rust-lang.org/2018/05/10/Rust-1.26.html](https://blog.rust-lang.org/2018/05/10/Rust-1.26.html). 
I guess this problem will resolve itself as soon as the build ending of he site is updated.

**Comment by MindFlavor** [comment]
Indeed there is a issue open for that: [https://github.com/onur/docs.rs/issues/205](https://github.com/onur/docs.rs/issues/205).

**Comment by MindFlavor** [comment]
Solved by docs.rs: [https://docs.rs/azure_sdk_for_rust/0.10.0/azure_sdk_for_rust/](https://docs.rs/azure_sdk_for_rust/0.10.0/azure_sdk_for_rust/)
