### ISSUE TITLE
Use builder pattern for Storage operations

### ISSUE THREAD

**Issue by MindFlavor** [MindFlavor/AzureSDKForRust#61]
- [x] Create container
- [x] List containers
- [x] Delete container
- [x] Get container ACLs
- [x] Set container ACLs
- [x] Get container properties
- [x] Acquire container lease
- [x] Break container lease
- [x] Release container lease
- [x] Renew container lease
- [x] List Blobs
- [x] Get Blob
- [x] Put block blob
- [x] Put page blob
- [x] Put append blob
- [x] Update page
- [x] Clear page
- [x] Put block
- [x] Put block list
- [x] Get block list
- [x] Delete blob
- [x] Delete blob snapshot
- [x] Acquire blob lease
- [x] Renew blob lease
- [x] ~~Change blob lease~~. Useless IMHO, Skipped for now.
- [x] Release blob lease
- [x] Break blob lease

**Comment by zpgaal** [comment]
I think blob_stream shall have the builder pattern too. The generated stream has a lifetime constraint that makes it impossible to move the stream to other futures for processing.

**Comment by MindFlavor** [comment]
I agree with you, I will open a new issue for that.

**Comment by MindFlavor** [comment]
Completed and published in [https://github.com/MindFlavor/AzureSDKForRust/releases/tag/0.10.0](https://github.com/MindFlavor/AzureSDKForRust/releases/tag/0.10.0).
