### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by mbrobbel** [MindFlavor/AzureSDKForRust#62]
First off: thank you for this nice crate :+1: 

I ran into a small issue today. Given a response body for a `QueryDocumentResponse` (`SELECT VALUE COUNT(*) ...`) like this:
```json
[32]
````
```rust
let body = "[32]".as_bytes();
let mut d: serde_json::Value = serde_json::from_slice(body).unwrap();
```
There is an `extract_result_json` function in `azure_sdk_for_rust::cosmos::QueryDocumentRequest` ([src](https://github.com/MindFlavor/AzureSDKForRust/blob/master/src/azure/cosmos/requests/document_requests.rs#L159)) which iterates over the documents and at some point uses `serde_json::value::Value::as_object_mut` ([src](https://github.com/MindFlavor/AzureSDKForRust/blob/master/src/azure/cosmos/requests/document_requests.rs#L195)) to check if the document is an object.
```rust
let map = doc.as_object_mut().unwrap();
```
However, in my example, the document is a `Number`, so the returned `Option` value is `None` causing the `unwrap` to panick:
```called `Option::unwrap()` on a `None` value```

**Comment by karataliu** [comment]
Can confirm the issue with query 'SELECT value count(1) FROM c', which returns [0].

extract_result_json may need to handle non object result.
https://github.com/MindFlavor/AzureSDKForRust/blob/405cf0bc29ef5a395363522b1af93b176ccb7f7a/src/azure/cosmos/requests/document_requests.rs#L195

Quick hack tried which prints the count:
```
match &doc{
    serde_json::Value::Number(a)   => print!("{}",a),
    _ => print!("Not number"),
};
```

**Comment by MindFlavor** [comment]
You are both right, the code assumes that everything has a `DocumentAttributes` so the `unwrap()` panics. I've created [https://github.com/MindFlavor/AzureSDKForRust/pull/63](https://github.com/MindFlavor/AzureSDKForRust/pull/63) based on [karataliu](https://github.com/karataliu)'s code: can you please check and tell me if you think it's ok? I've tested with [mbrobbel](https://github.com/mbrobbel)'s `COUNT` and it seems to work:

![repro](https://user-images.githubusercontent.com/431595/42641934-031554dc-85f6-11e8-89e3-b9d78ec48daf.png)

```bash
✔ 17:00 mindflavor@arch ~/src/rust/AzureSDKForRust $ cargo run --example query_document00 pollo gigi 'SELECT value COUNT(1) FROM c'
   Compiling azure_sdk_for_rust v0.9.0 (file:///home/mindflavor/src/rust/AzureSDKForRust)                                                                                                      
    Finished dev [unoptimized + debuginfo] target(s) in 6.89s                                                                                                                                  
     Running `target/debug/examples/query_document00 pollo gigi 'SELECT value COUNT(1) FROM c'`
As JSON:
QueryDocumentResponse { query_response_meta: QueryResponseMeta { rid: "FRgeAJ2OFAE=", count: 1 }, results: [QueryResult { document_attributes: None, result: Number(2) }], additional_headers: QueryDocumentResponseAdditonalHeaders { continuation_token: None, charge: 2.22 } }
2
```

Thank you in advance,
Francesco

**Comment by karataliu** [comment]
Looks good from my side, it'll make `.execute::<u32>();` work now  :+1:

**Comment by mbrobbel** [comment]
Thanks!
