### ISSUE TITLE
Logs during process

### ISSUE THREAD

**Issue by zpgaal** [MindFlavor/AzureSDKForRust#76]
It seems as the sdk logs to the console and I see no option to turn it off.
(I'm using the git version and not the released one)

**Comment by MindFlavor** [comment]
Yes you are right, I have left some `println!`s around. I will try and clean them up ASAP. 
Sorry!

**Comment by zpgaal** [comment]
Thanks, that was fast :)

**Comment by MindFlavor** [comment]
Let's hope is enough! Please reopen the issue if this keeps happening!
