### ISSUE TITLE
list_blob always return with error

### ISSUE THREAD

**Issue by zpgaal** [MindFlavor/AzureSDKForRust#78]
(On the head for the git)

List blob always return with error:
`ResponseParsingError(PathNotFound("AccessTier"))`
Sample:

```
client.list_blobs()
            .with_container_name(container)
            .with_include_metadata()
            .finalize()
            .map(|iv| {
                trace!("List containers returned {} containers.", iv.incomplete_vector.len());
                unimplemented!() // never called
            }).map_err(|err| {
                println!("{:?}", err);
            })
```

According to the logs (just removed :) ) it gets the result in xml from the server, but it never gets to the map function.

**Comment by MindFlavor** [comment]
The error means the returned XML does not contain the `AccessTier` node. According to this [https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs) it should be the case, along with the `AccessTierInferred` node for the newest v2 storage accounts. 

Could be you are using classic or V1 storage accounts? Can you please check and get back to me? It's in the portal pane, in overview, under `Account kind`:

![image](https://user-images.githubusercontent.com/431595/44272935-6c183d00-a23e-11e8-8d3a-7a99af928be1.png)

**Comment by zpgaal** [comment]
it is "Storage (general purpose v1)"

By the way if I make access_tier option<String> it seems to be ok.

**Comment by MindFlavor** [comment]
Ok so my supposition was right. 
Do you mind upgrading to v2 and see if the error disappears? 
I was planning to support v2 only (I should have made it clear in the README tough)!

Thank you!

**Comment by zpgaal** [comment]
Sorry, but the DB cannot be upgraded. Its a live DB and I'm experimenting to port some of our tools into rust.

**Comment by MindFlavor** [comment]
I see, makes sense. I will do some experiment and try to support v1 too (should just mean some fields will become Optional). Let's leave this open.

**Comment by zpgaal** [comment]
ok, thanks a lot.
(Nice job, great lib easy to understand)

**Comment by MindFlavor** [comment]
I have a pr to address this problem. I haven't checked all the methods with v1 so please open other issues if something does not work as expected! 

Thank you!
:+1:
