### ISSUE TITLE
link not working

### ISSUE THREAD

**Issue by letubert** [MindFlavor/AzureSDKForRust#97]
On the repo main page, the link 
[https://mindflavor.github.io/AzureSDKForRust/azure_sdk_for_rust](url) is not working

**Comment by MindFlavor** [comment]
Yes I used to have the standard jekyll GitHub page but I've removed it because I wanted something more shiny. I'll reenable it ASAP until I'm able to make up something better.

**Comment by MindFlavor** [comment]
I've created a single-page Jekyll site based on [https://github.com/t413/SinglePaged](https://github.com/t413/SinglePaged).  It can - and should - be improved upon but at least there is no more 404!
