### ISSUE TITLE
uri is not escaped properly

### ISSUE THREAD

**Issue by zpgaal** [MindFlavor/AzureSDKForRust#98]
GetBlob fails for "image - copy(1).png" with Error preparing HTTP request: invalid uri character.

**Comment by zpgaal** [comment]
I'm not sure but this could be a solution:

in rest_client.rs convert uri from url.
```
request.method(http_method.clone()).uri(url.to_string());
```

**Comment by MindFlavor** [comment]
I can confirm the bug. I've been lazy with the escaping it seems :).

**Comment by MindFlavor** [comment]
A solution could be replacing the `uri` code with something like this:

```rust
        let mut uri = format!(
            "https://{}.blob.core.windows.net/{}/{}",
            self.client().account(),
            utf8_percent_encode(&container_name, COMPLETE_ENCODE_SET),
            utf8_percent_encode(&blob_name, COMPLETE_ENCODE_SET)
        );  
```

I do not remember right now if the container can have non valid HTTP characters so it's safest to escape it anyway.

I will have to modify every builder to call the `utf8_percent_encode` function. Another way is to write. I'll think about it in a bit.

**Comment by MindFlavor** [comment]
If you have the time I could use an hand testing the solution. Right now I have only changed `GET` blob, you can find the code in this branch: [issue/98](/MindFlavor/AzureSDKForRust/tree/issue/98).

**Comment by MindFlavor** [comment]
I have removed "testing needed" here and added to the above PR (which should contain the fix for all the blob storage methods).
