### ISSUE TITLE
What do you mean with account?

### ISSUE THREAD

**Issue by johnfercher** [MindFlavor/AzureSDKForRust#99]
Following the [Azure Cosmos Db Tutorial](https://docs.microsoft.com/pt-br/azure/cosmos-db/sql-api-dotnetcore-get-started) there are no account involved. There is a master key (primary key), but I'm lost with this account.

I'm getting the error
```
Err(HyperError(Error { kind: Connect, cause: Some(Os { code: 11001, kind: Other, message: "Este host não é conhecido." }) }))
```

**Comment by johnfercher** [comment]
I found. When you create a CosmosDB instance you receive a URL like https://test.documents.azure.com:443/, the account is the first part of the URL, in this case test.

https://{account}.documents.azure.com:443/

**Comment by MindFlavor** [comment]
Hi Johnathan,
it's the unique account ID that identifies your Cosmos DB Account. In the page you linked is in "Step 1 - Point 3".  
Without it the SDK cannot build your databases's URI.

**Comment by johnfercher** [comment]
@MindFlavor, thanks for your incredible crate and your support. It's working now, I created a pull request which adds some informations that I think was not explicit.

**Comment by MindFlavor** [comment]
Thank you for contributing! 
This is a community effort so I don't deserve all the credit. There are other contribs: now you are one of them!
